# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20180614_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='CodUbicacion',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='ConduccionDeHorasMetros',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='DistanciaRecorrida',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='GPSCorrecto',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='NumeroReportesEnviados',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='SatelitesUsados',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='TiempoReal',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='ValorADC',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='ValorEntradasYsalidas',
        ),
        migrations.AddField(
            model_name='tracking',
            name='interno',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tracking',
            name='placa',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
